name: PR-Build-Staging
on:
  pull_request:
    branches:
      - staging

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          ref: staging
            
      - name: Install and Build
        run: |
          npm install
          npm run build